services:
  app:
    build: .
    container_name: cart-api
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    depends_on:
      postgres_db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - SSL_MODE=${DB_SSL_MODE}
      - DB_HOST=postgres_db
      - HTTP_PORT=${HTTP_PORT}

  postgres_db:
    image: postgres:15-alpine
    container_name: cart-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

    ports:
      - "${DB_EXTERNAL_PORT}:${DB_PORT}"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    image: gomicro/goose
    container_name: cart-migrate
    volumes:
      - ./migrations:/migrations
    command: /bin/goose -dir /migrations postgres "postgres://${DB_USER}:${DB_PASSWORD}@postgres_db:${DB_PORT}/${DB_NAME}?sslmode=${DB_SSL_MODE}" up
    depends_on:
      postgres_db:
        condition: service_healthy

volumes:
  pg_data: