services:
  app:
    build: .
    depends_on:
      - db
      - migrations
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DB_SSL_MODE=${DB_SSL_MODE}
      - HTTP_PORT=${HTTP_PORT}

  db:
    image: postgres:15-alpine
    ports:
      - ${DB_EXTERNAL_PORT}:${DB_PORT}
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DB_SSL_MODE=${DB_SSL_MODE}
    volumes:
      - db_data:/var/lib/postgresql/data

  migrations:
    image: gomicro/goose:latest
    volumes:
      - ./migrations:/migrations
    command: /bin/goose -dir /migrations postgres "postgres://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/${DB_NAME}?sslmode=${DB_SSL_MODE}" up
    depends_on:
      - db

  web:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - ${WEB_PORT}:${WEB_PORT}
    depends_on:
      - app

volumes:
  db_data: