apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cart-api
  name: cart-api
  namespace: test
spec:
  replicas: 5
  selector:
    matchLabels:
      app: cart-api
  strategy: {}
  template:
    metadata:
      labels:
        app: cart-api
    spec:
      containers:
      - image: innowise-cart-api-app:latest
        name: innowise-cart-api-app
        ports:
        - containerPort: 8080
        resources: {}
status: {}
